# Generated by Django 5.1.4 on 2024-12-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=15)),
                ('position', models.CharField(max_length=30)),
                ('Contact', models.IntegerField()),
                ('city', models.CharField(max_length=34)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
